version: "3.7"
services:
  server:
    image: tablee/code-push-server:v0.5.2
    container_name: codepush_server
    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
      - ./config.js:/config.js
    environment:
      DOWNLOAD_URL: "https://codepush.xxxxx.xx"
      MYSQL_HOST: "codepush_db"
      MYSQL_PORT: "3306"
      MYSQL_USERNAME: "codepush"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "codepush"
      STORAGE_DIR: "/data/storage"
      DATA_DIR: "/data/tmp"
      NODE_ENV: "production"
      CONFIG_FILE: "/config.js"
      REDIS_HOST: "codepush_redis"
      REDIS_PORT: "6379"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - codepush
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7.23
    container_name: codepush_db
    volumes:
      - data-mysql:/var/lib/mysql
      - ./sql/codepush-all.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "On"
    networks:
      - codepush
  redis:
    image: redis:4.0.11-alpine
    container_name: codepush_redis
    volumes:
      - data-redis:/data
    ports:
      - "6388:6379"
    networks:
      - codepush
networks:
  codepush:
    external: true
volumes:
  data-storage:
  data-tmp:
  data-mysql:
  data-redis:
